import os
import sys
import shutil
import stat
import hashlib

sys.stdout.reconfigure(encoding='utf-8')

ROOT_DIR = os.path.abspath('.')
REVIEW_DIR = os.path.abspath('REVIEW_BEFORE_DELETE')

def is_reparse_point(path):
    try:
        s = os.stat(path, follow_symlinks=False)
        return bool(s.st_file_attributes & stat.FILE_ATTRIBUTE_REPARSE_POINT)
    except Exception:
        return False

# Plan categories
to_move = [] # tuple of (rel_path, category, reason, kept_replacement)

# 1. MS Word temp lock files
for f in [
    'docs/reports/~$oCaoTienDoMoc2_NguyenHuuDung_11235559_final.docx',
    'docs/reports/~$oCaoTienDoMoc2_NguyenHuuDung_11235559_with_images.docx'
]:
    if os.path.exists(f):
        to_move.append((f, 'TEMP_LOCK', 'Word lock file sinh tự động, không chứa dữ liệu hữu ích', 'docs/reports/BaoCaoTienDoMoc2_NguyenHuuDung_11235559_final.docx'))

# 2. Outdated DOCX drafts
for f, reason in [
    ('docs/reports/BaoCaoTienDoMoc2_NguyenHuuDung_11235559_with_images.docx', 'Bản nháp M2 cũ chứa số liệu phân tách 697/123/382 mâu thuẫn với Mốc 1'),
    ('docs/reports/BaoCaoTienDoMoc2_NguyenHuuDung_11235559_M1_aligned.docx', 'Bản nháp căn chỉnh trung gian trước khi hoàn thiện bản final')
]:
    if os.path.exists(f):
        to_move.append((f, 'OUTDATED_DOC', reason, 'docs/reports/BaoCaoTienDoMoc2_NguyenHuuDung_11235559_final.docx'))

# 3. Duplicate binary_binary image files
p2d = 'dataset/Vinmec/Vinmec_2d/annotations'
if os.path.exists(p2d):
    for f in os.listdir(p2d):
        if f.endswith('_binary_binary.PNG'):
            rel = os.path.join(p2d, f)
            base = f.replace('_binary_binary.PNG', '_binary.PNG')
            to_move.append((rel, 'DUPLICATE_IMAGE_2D', 'Trùng lặp 100% SHA256 do lỗi kịch bản sinh tên file kép', os.path.join(p2d, base)))

p3d = 'dataset/Vinmec/Vinmec_3d/annotations'
if os.path.exists(p3d):
    for f in os.listdir(p3d):
        if f.endswith('_binary_binary.PNG'):
            rel = os.path.join(p3d, f)
            base = f.replace('_binary_binary.PNG', '_binary.PNG')
            to_move.append((rel, 'DUPLICATE_IMAGE_3D', 'Trùng lặp 100% SHA256 do lỗi kịch bản sinh tên file kép', os.path.join(p3d, base)))

# 4. Duplicate evaluation snapshot directories
eval_dups = [
    ('evaluation/e2e_validation_2026-10-01', 'Bản sao snapshot trùng lặp 100% SHA256 với vinmec_unet_val', 'evaluation/vinmec_unet_val'),
    ('evaluation/product_validation_2026-10-01', 'Bản sao snapshot trùng lặp 100% SHA256 với vinmec_unet_val', 'evaluation/vinmec_unet_val'),
    ('evaluation/retrain_2d_2026-10-03/previous_validation', 'Bản sao snapshot trùng lặp 100% SHA256 với vinmec_unet_val', 'evaluation/vinmec_unet_val'),
    ('evaluation/full_dataset_2026-10-03/Vinmec_Split_CEUS_val', 'Bản sao snapshot trùng lặp 100% SHA256 với Vinmec_CEUS_val', 'evaluation/full_dataset_2026-10-03/Vinmec_CEUS_val')
]

for src_dir, reason, kept_dir in eval_dups:
    if os.path.exists(src_dir):
        for root, dirs, files in os.walk(src_dir):
            for f in files:
                rel = os.path.relpath(os.path.join(root, f), '.')
                rel_kept = os.path.relpath(os.path.join(kept_dir, os.path.relpath(root, src_dir), f), '.')
                to_move.append((rel, 'DUPLICATE_EVAL_DIR', reason, rel_kept))

# 5. Compiler & test cache
cache_dirs = ['.pytest_cache', '.ruff_cache']
for cd in cache_dirs:
    if os.path.exists(cd):
        for root, dirs, files in os.walk(cd):
            for f in files:
                rel = os.path.relpath(os.path.join(root, f), '.')
                to_move.append((rel, 'TOOL_CACHE', 'Cache tự sinh của công cụ test/linter', '[Auto-regenerated by tool]'))

for root, dirs, files in os.walk('.', topdown=True):
    dirs[:] = [d for d in dirs if d not in {'.git', '.venv', 'REVIEW_BEFORE_DELETE'} and not is_reparse_point(os.path.join(root, d))]
    if os.path.basename(root) == '__pycache__':
        for f in files:
            rel = os.path.relpath(os.path.join(root, f), '.')
            to_move.append((rel, 'PYTHON_CACHE', 'Bytecode cache *.pyc tự sinh của Python', '[Auto-compiled by Python]'))

print(f"Total files identified to move to REVIEW_BEFORE_DELETE: {len(to_move)}")

# Perform safe move
moved_count = 0
for rel_path, cat, reason, kept in to_move:
    src = os.path.abspath(rel_path)
    dst = os.path.join(REVIEW_DIR, rel_path)
    if os.path.exists(src):
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.move(src, dst)
        moved_count += 1

print(f"Successfully moved {moved_count} files into REVIEW_BEFORE_DELETE/ while preserving folder hierarchy.")

# Clean up empty parent directories left behind in source
for src_dir, _, _ in eval_dups:
    if os.path.exists(src_dir) and not os.listdir(src_dir):
        os.removedirs(src_dir)

for cd in cache_dirs:
    if os.path.exists(cd) and not os.listdir(cd):
        shutil.rmtree(cd, ignore_errors=True)

for root, dirs, files in os.walk('.', topdown=False):
    if any(p in root for p in ['.git', '.venv', 'REVIEW_BEFORE_DELETE']):
        continue
    if os.path.basename(root) == '__pycache__' and not os.listdir(root):
        os.rmdir(root)

print("Empty cache/duplicate directories cleaned up from source workspace.")
